# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://nuxqa4.avtest.ink/es/ofertas-destinos/ofertas-de-vuelos")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.CSS_SELECTOR, ".routes-lowest-price-list_grid--cols-3 > .routes-lowest-price-list_item:nth-child(2) .route-lowest-price_image").click()
    self.driver.execute_script("window.scrollTo(0,387)")
    self.driver.find_element(By.CSS_SELECTOR, ".ngb-dp-day:nth-child(4) > .price-range--high .custom-day_day").click()
    self.driver.find_element(By.CSS_SELECTOR, ".arrival .custom-day_day").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui-overlay")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-control_selector_item:nth-child(1) .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, "#searchButton > .button_label").click()
    element = self.driver.find_element(By.ID, "accordionGroup13217")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c12-2 .price").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fare8 .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".journey_price_fare > .ng-tns-c12-56").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fare8 .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".summary_trigger").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".departure")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".price-breakdown-header_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".summary_close_btn > .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".page_button > .button_label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".container-wrap:nth-child(3) .grid-col")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
